

### Create Contact
POST http://localhost:3000/razorpay/create-contact
Content-Type: application/json

{
  "phoneNumber": "9876543210",
  "name": "John Does"
}

### Create Fund Account with Bank Details
POST http://localhost:3000/razorpay/create-fund-account
Content-Type: application/json

{
  "contactId": "cont_R2vfwe8Df8gEgp",
  "payoutDetails": {
    "payoutMethod": "BANK_ACCOUNT",
    "bankDetails": {
      "accountHolderName": "John Doe",
      "accountNumber": "1234567890",
      "ifscCode": "HDFC0000001"
    }
  }
}


### Create Fund Account with VPA
POST http://localhost:3000/razorpay/create-fund-account
Content-Type: application/json

{
  "contactId": "cont_R2vieAAUYGOWDw",
  "payoutDetails": {
    "payoutMethod": "VPA",
    "vpaDetails": {
      "vpa": "john@okicici"
    }
  }
}


### Create Order
POST http://localhost:3000/razorpay/create-order
Content-Type: application/json

{
  "order": {
    "amount": 50000,
    "currency": "INR",
    "notes": {
      "customer_name": "Akhil Raj",
      "customer_contact": "+916300045929",
      "customer_email": "kssakhilraj@gmail.com",
      "description": "Dummy payment order for testing"
    }
  }
}

### Create payment link for dummy order
POST http://localhost:3000/razorpay/create-payment-link
Content-Type: application/json

{
  "orderId": "order_RVG7OVWChJbSJK"
}

