-- This migration is a placeholder for encrypting existing Aadhaar data
-- Since we cannot encrypt existing data in SQL (requires the encryption key from Node.js),
-- you need to run a data migration script after deploying the code changes.
--
-- The script should:
-- 1. Fetch all DriverDocuments records
-- 2. For each record, if aadharNumberEncrypted is still a UUID (default value):
--    - Decrypt/retrieve the original Aadhaar number (if stored elsewhere)
--    - Encrypt it using the new AES encryption
--    - Update the aadharNumberEncrypted field
--
-- Note: If original Aadhaar numbers are not available, this field will remain as UUID
-- and new submissions will use proper encryption.
