### Create Booking (Customer)
POST http://localhost:3000/bookings/customer
Authorization: Bearer 6300045929
Content-Type: application/json

{
  "dropAddress": {
    "formattedAddress": "QJ4X+G6, Vallichira, Nechipuzhoor, Kerala 686635, India",
    "latitude": 9.7560312,
    "longitude": 76.6479833
  },
  "pickupAddress": {
    "formattedAddress": "Rama Bhaathi Nilayam, Plot 122/A, 301, Moti Nagar Phase III, Kalyan Nagar, Moti Nagar, Hyderabad, Telangana 500114, India",
    "latitude": 17.4510495,
    "longitude": 78.42151087
  },
  "package": {
    "packageType": "PERSONAL",
    "productType": "AGRICULTURAL",
    "agricultural": {
      "productName": "12",
      "approximateWeight": 12,
      "weightUnit": "KG"
    },
    "transportDocUrls": []
  },
  "selectedVehicleType": "THREE_WHEELER"
}


