

# Check server url https://hello-truck-server.fly.dev/


POST http://localhost:3000/auth/customer/send-otp
Content-Type: application/json

{
  "phoneNumber": "6300041123"
}

### Verify OTP
POST http://localhost:3000/auth/customer/verify-otp
Content-Type: application/json

{
  "phoneNumber": "6300041123",
  "otp": "123456"
}

### Create saved address
POST http://localhost:3000/customer/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiZDYzZDI3NjItZWJmZi00NTE5LWExOGItMWNiNzI4ODE5NWE4IiwicGhvbmVOdW1iZXIiOiI2MzAwMDQxMTIzIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1MjYxOTIwLCJleHAiOjE3NTUyNjI4MjB9.vA2eKByL64x7gP40X_pAydheeqt7IgIcehRJoA6sxyo

{
  "name": "Home 2",
  "address": {
    "formattedAddress": "123, Main Street, Mumbai, Maharashtra, 400001",
    "addressDetails": "House No. 123, Street Name, City, State, 400001",
    "latitude": 19.0760,
    "longitude": 72.8777
  },
  "contactName": "John Doe",
  "contactPhone": "6300041123",
  "noteToDriver": "Please deliver to the main entrance",
  "isDefault": true
}

### Get saved addresses
GET http://localhost:3000/customer/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiZDYzZDI3NjItZWJmZi00NTE5LWExOGItMWNiNzI4ODE5NWE4IiwicGhvbmVOdW1iZXIiOiI2MzAwMDQxMTIzIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1MjYxOTIwLCJleHAiOjE3NTUyNjI4MjB9.vA2eKByL64x7gP40X_pAydheeqt7IgIcehRJoA6sxyo

### Create user profile
POST http://localhost:3000/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiZDYzZDI3NjItZWJmZi00NTE5LWExOGItMWNiNzI4ODE5NWE4IiwicGhvbmVOdW1iZXIiOiI2MzAwMDQxMTIzIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1MjYxOTIwLCJleHAiOjE3NTUyNjI4MjB9.vA2eKByL64x7gP40X_pAydheeqt7IgIcehRJoA6sxyo

{
  "firstName": "John",
  "lastName": "Doe",
  "referralCode": "123456",
  "gstDetails": {
    "gstNumber": "27AAACF2234C1Z7",
    "businessName": "Hello Truck Pvt Ltd",
    "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
  }
}
### Get user profile
GET http://localhost:3000/customer/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiZDYzZDI3NjItZWJmZi00NTE5LWExOGItMWNiNzI4ODE5NWE4IiwicGhvbmVOdW1iZXIiOiI2MzAwMDQxMTIzIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1MjYxOTIwLCJleHAiOjE3NTUyNjI4MjB9.vA2eKByL64x7gP40X_pAydheeqt7IgIcehRJoA6sxyo

### Update user profile
PUT http://localhost:3000/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

{
  "email": "john.doe@example.com"
}

### get gst details
GET http://localhost:3000/customer/gst/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRhMWM4YmEtOTA1My00MmEzLWJjZmMtZmU3MzJlMDFlYjA2IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6ZmFsc2UsImlhdCI6MTc1MzM4NzA0MywiZXhwIjoxNzUzMzg3OTQzfQ.jsEU0SpQGI9OwKcWYaIHxbO6b3K6xRr7ajcrCeElzHI

### Add GST details
POST http://localhost:3000/customer/gst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRhMWM4YmEtOTA1My00MmEzLWJjZmMtZmU3MzJlMDFlYjA2IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6ZmFsc2UsImlhdCI6MTc1MzM4NzA0MywiZXhwIjoxNzUzMzg3OTQzfQ.jsEU0SpQGI9OwKcWYaIHxbO6b3K6xRr7ajcrCeElzHI

{
  "gstNumber": "27AAACF2234C1Z8",
  "businessName": "Hello Truck Pvt Ltd",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Update GST details
PUT http://localhost:3000/customer/gst/b394e6f4-e40f-4a5e-a6ca-1cf715c4f95c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRhMWM4YmEtOTA1My00MmEzLWJjZmMtZmU3MzJlMDFlYjA2IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6ZmFsc2UsImlhdCI6MTc1MzM4NzA0MywiZXhwIjoxNzUzMzg3OTQzfQ.jsEU0SpQGI9OwKcWYaIHxbO6b3K6xRr7ajcrCeElzHI

{

  "gstNumber": "27AAACF2234C1Z5",
  "businessName": "Hello Truck Pvt Ltd Updated",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Deactivate GST details
POST http://localhost:3000/customer/gst/deactivate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

{
  "id": "da41269f-9325-492b-9aad-045432a1003a"
}



