

# Check server url https://hello-truck-server.fly.dev/


POST http://localhost:3000/auth/customer/send-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929"
}

### Verify OTP
POST http://localhost:3000/auth/customer/verify-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929",
  "otp": "123456"
}

### Create saved address
POST http://localhost:3000/customer/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{
  "name": "Home 2",
  "address": {
    "formattedAddress": "123, Main Street, Mumbai, Maharashtra, 400001",
    "addressDetails": "House No. 123, Street Name, City, State, 400001",
    "latitude": 19.0760,
    "longitude": 72.8777
  },
  "contactName": "John Doe",
  "contactPhone": "6300041123",
  "noteToDriver": "Please deliver to the main entrance",
  "isDefault": true
}

### Get saved addresses
GET http://localhost:3000/customer/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
### Get default saved address
GET http://localhost:3000/customer/addresses/default
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
### Create user profile
POST http://localhost:3000/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{
  "firstName": "John",
  "lastName": "Doe",
  "referralCode": "123456",
  "gstDetails": {
    "gstNumber": "27AAACF2234C1Z7",
    "businessName": "Hello Truck Pvt Ltd",
    "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
  }
}
### Get user profile
GET http://localhost:3000/customer/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
### Update user profile
PUT http://localhost:3000/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{
  "email": "john.doe@example.com"
}

### get gst details
GET http://localhost:3000/customer/gst/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
### Add GST details
POST http://localhost:3000/customer/gst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{
  "gstNumber": "27AAACF2234C1Z8",
  "businessName": "Hello Truck Pvt Ltd",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Update GST details
PUT http://localhost:3000/customer/gst/b394e6f4-e40f-4a5e-a6ca-1cf715c4f95c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{

  "gstNumber": "27AAACF2234C1Z5",
  "businessName": "Hello Truck Pvt Ltd Updated",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Deactivate GST details
POST http://localhost:3000/customer/gst/deactivate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiMTRiYjgwYjYtZGMyMC00Mjg1LWJiNWQtOWQ1ZTcwYTljOWExIiwicGhvbmVOdW1iZXIiOiI2MzAwMDQ1OTI5IiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzU1NDU3NjM2LCJleHAiOjE3NTU0NTg1MzZ9.9O8GdkEOLtl_nMBEGroDwterOwSa-hiMuido7DhrSTc
{
  "id": "da41269f-9325-492b-9aad-045432a1003a"
}


