
# Check server url https://hello-truck-server.fly.dev/
@base_url = https://hello-truck-server1.fly.dev

POST {{base_url}}/auth/driver/send-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929"
}

### Verify OTP
POST {{base_url}}/auth/driver/verify-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929",
  "otp": "123456"
}

### Get Profile
GET {{base_url}}/driver/profile?includeVehicle=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImExZjkzZTU2LTBmODktNDVkYy05OTk2LTAxN2Y4ODA1MjkzNCIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOnRydWUsInNlc3Npb25JZCI6ImRkOTZmMTk0LTliZjktNDQxMy1hMDdkLWFlMmQ5NjcwNDI2NCIsImlhdCI6MTc2NTgyNzQ5MywiZXhwIjoxNzY1ODI4MzkzfQ.csPlZSqZYSvWuaDS1Pf5aKQrugN4u_netNG0MULUIuo

### Get Wallet Logs
GET {{base_url}}/driver/profile/wallet-logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImNmYjJlNmIxLTQyYWEtNGEyNi04MmJmLWM1YzM4MGM3NjFhZiIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOmZhbHNlLCJzZXNzaW9uSWQiOiI4NWNlNDEzYy1jOGIxLTQzNWEtOTgzMi03OGVhZGFiMGVlODUiLCJpYXQiOjE3NjU2NDUwMzEsImV4cCI6MTc2NTY0NTkzMX0.SuOlxO52rdlbGViC6qaWLMSBoNiZh-MfySPNvmjA5o0

### Get Transaction Logs (with full booking and payout details)
GET http://localhost:3000/driver/profile/transaction-logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImNmYjJlNmIxLTQyYWEtNGEyNi04MmJmLWM1YzM4MGM3NjFhZiIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOmZhbHNlLCJzZXNzaW9uSWQiOiI4NWNlNDEzYy1jOGIxLTQzNWEtOTgzMi03OGVhZGFiMGVlODUiLCJpYXQiOjE3NjU2NDUwMzEsImV4cCI6MTc2NTY0NTkzMX0.SuOlxO52rdlbGViC6qaWLMSBoNiZh-MfySPNvmjA5o0

### TEMPORARY: Create Test Transaction Log (with payout)
POST http://localhost:3000/driver/profile/test/create-transaction-log
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImNmYjJlNmIxLTQyYWEtNGEyNi04MmJmLWM1YzM4MGM3NjFhZiIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOmZhbHNlLCJzZXNzaW9uSWQiOiI4NWNlNDEzYy1jOGIxLTQzNWEtOTgzMi03OGVhZGFiMGVlODUiLCJpYXQiOjE3NjU2NDUwMzEsImV4cCI6MTc2NTY0NTkzMX0.SuOlxO52rdlbGViC6qaWLMSBoNiZh-MfySPNvmjA5o0

### TEMPORARY: Create Test Wallet Log
POST http://localhost:3000/driver/profile/test/create-wallet-log
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImNmYjJlNmIxLTQyYWEtNGEyNi04MmJmLWM1YzM4MGM3NjFhZiIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOmZhbHNlLCJzZXNzaW9uSWQiOiI4NWNlNDEzYy1jOGIxLTQzNWEtOTgzMi03OGVhZGFiMGVlODUiLCJpYXQiOjE3NjU2NDUwMzEsImV4cCI6MTc2NTY0NTkzMX0.SuOlxO52rdlbGViC6qaWLMSBoNiZh-MfySPNvmjA5o0


### Get Address
GET http://localhost:3000/driver/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRyaXZlciIsInVzZXJJZCI6ImExZjkzZTU2LTBmODktNDVkYy05OTk2LTAxN2Y4ODA1MjkzNCIsInBob25lTnVtYmVyIjoiNjMwMDA0NTkyOSIsImhhc0NvbXBsZXRlZE9uYm9hcmRpbmciOnRydWUsInNlc3Npb25JZCI6ImRkZDRjMTdkLTUxMzMtNDU4NS04Nzk3LTA5ODdhYWIzNWM1ZCIsImlhdCI6MTc2NTgwNjc3MSwiZXhwIjoxNzY1ODA3NjcxfQ.TYdMVTEP13_ZYkXxZqVaOTweSzlvAB5JNcP3gG0Y5iY
